name: Build and Publish Docker Image

on:
  push:
    branches:
      - "main"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub Registry
        run: docker login -u siroo2137 -p ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Fetch the latest release of Infrared
        run: gh release download -R lhridder/infrared -p 'infrared_Linux_x86_64.tar.gz'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract the latest release of Infrared
        run: tar -xvf infrared_Linux_x86_64.tar.gz

      - name: Build the latest Docker image
        run:  docker build . --file Dockerfile --tag siroo2137/infrared-egg:latest

      - name: Push the latest Docker image
        run: docker push siroo2137/infrared-egg:latest
