name: Build and Publish Docker Image

on:
  push:
    branches:
      - "main"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub Registry
        run: docker login -u siroo2137 -p ${{ secrets.DOCKER_TOKEN }}
      
      - name: Fetch the latest release of Infrared
        run: wget https://github.com/siroo2137/infrared/raw/refs/heads/master/out/infrared
        
      - name: Allow execution of Infrared
        run: chmod +x infrared

      - name: Build the latest Docker image
        run:  docker build . --file Dockerfile --tag siroo2137/infrared-egg:latest

      - name: Push the latest Docker image
        run: docker push siroo2137/infrared-egg:latest
